### ISSUE TITLE
Data directory setting

### ISSUE THREAD

**Issue by teamon** [ANXS/mysql#13]
I know it's not just simple config file change but also moving the data dir after apt package install, but do you have any plans to support that? 

I'll try to do that but and submit PR but I'd like to let you know in case someone is already working on this.

**Comment by teamon** [comment]
I just checked and this is what I ended up with few months ago:

![](https://dl.dropboxusercontent.com/s/v8juh21jbogmx3c/2015-01-10%20at%2017.46.png?dl=0)

I can't remember now if this was enough or I just abandoned the thing (most probably it's not 100% solution)

**Comment by jnakatsui** [comment]
@teamon Thanks this was helpful :+1:
