### ISSUE TITLE
Make MariaDB installation posible 

### ISSUE THREAD

**Issue by hrstoyanov** [ANXS/mysql#39]
Can you move this from vars to defaults?
```
mysql_packages:
  - mariadb-client
  - mariadb-server
  - python-mysqldb
```

**Comment by farridav** [comment]
I can see that the var files are keyed on distribution, so am assuming this was an attempt to support multiple distributions... that said, within tasks/install.yml we are using the `apt` resource, so we don't support any distro other than ubuntu... in short, sure we can move those vars into defaults.. https://github.com/ANXS/mysql/pull/40
